version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 10 && python new_worker.py"
    volumes:
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 20 && python orchestrator.py"
    volumes:
        - .:/code
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zoo
    ports:
        - 80:5000
    restart: on-failure    

  
